"""
Export functionality for summaries and content
"""

import streamlit as st
from datetime import datetime
import markdown
from io import BytesIO

def render_export_section():
    """Render export section"""
    
    st.markdown("### 📤 Export Options")
    
    export_format = st.radio(
        "Format",
        ["Markdown", "Plain Text", "PDF"],
        horizontal=True
    )
    
    # Content to export
    export_content = generate_export_content()
    
    if export_format == "Markdown":
        filename = f"summary_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
        content = export_as_markdown(export_content)
        
        st.download_button(
            label="📥 Download Markdown",
            data=content,
            file_name=filename,
            mime="text/markdown",
            use_container_width=True
        )
        
        with st.expander("👁️ Preview"):
            st.markdown(content)
    
    elif export_format == "Plain Text":
        filename = f"summary_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt"
        content = export_as_text(export_content)
        
        st.download_button(
            label="📥 Download Text",
            data=content,
            file_name=filename,
            mime="text/plain",
            use_container_width=True
        )
        
        with st.expander("👁️ Preview"):
            st.text(content)
    
    elif export_format == "PDF":
        st.info("📝 PDF export requires additional setup. Use Markdown or Text for now.")
        st.markdown("**Alternative:** Download Markdown and convert using online tools.")

def generate_export_content():
    """Generate content for export"""
    content_data = st.session_state.current_content
    
    export_data = {
        'title': content_data.get('title', 'Untitled'),
        'source_type': content_data['source_type'],
        'date': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
        'summary': st.session_state.current_summary,
        'insights': st.session_state.current_insights,
        'questions': st.session_state.current_questions,
        'transformation': st.session_state.current_transformation
    }
    
    return export_data

def export_as_markdown(data: dict) -> str:
    """Format as Markdown"""
    
    md = f"""# {data['title']}

**Generated:** {data['date']}  
**Source Type:** {data['source_type'].upper()}

---

## 📝 Summary

{data['summary'] or '_No summary generated_'}

"""
    
    if data['insights']:
        md += f"""
---

## 💡 Key Insights

{data['insights']}

"""
    
    if data['questions']:
        md += f"""
---

## ❓ Questions

{data['questions']}

"""
    
    if data['transformation']:
        md += f"""
---

## 🔄 Transformed Content

{data['transformation']}

"""
    
    md += """
---

*Generated by Content Intelligence Platform*
"""
    
    return md

def export_as_text(data: dict) -> str:
    """Format as plain text"""
    
    text = f"""{data['title']}
{'=' * len(data['title'])}

Generated: {data['date']}
Source Type: {data['source_type'].upper()}

{'=' * 60}

SUMMARY
{'=' * 60}

{data['summary'] or 'No summary generated'}

"""
    
    if data['insights']:
        text += f"""
{'=' * 60}

KEY INSIGHTS
{'=' * 60}

{data['insights']}

"""
    
    if data['questions']:
        text += f"""
{'=' * 60}

QUESTIONS
{'=' * 60}

{data['questions']}

"""
    
    if data['transformation']:
        text += f"""
{'=' * 60}

TRANSFORMED CONTENT
{'=' * 60}

{data['transformation']}

"""
    
    text += """
{'=' * 60}

Generated by Content Intelligence Platform
"""
    
    return text
